# Site settings
title: Gaussian Process School
year: 2013
location: Kampala, Uganda
banner: Kampala_26.08.2009_13-00-45.jpg
email: info@datascienceafrica.org
description: > # this means to ignore newlines until "baseurl:"
  The 2013 Gaussian Process School held at the University of Makerere
baseurl: "/gpss2013/" # the subpath of your site, e.g. /blog/
url: "http://www.datascienceafrica.org" # the base hostname & protocol for your site
twitter_username: datsciAfrica
logo_url: img/logo.png
github_username:  datsciafrica



school:
  hosts:
  - {name: John Quinn, url: "http://cit.mak.ac.ug/staff/jquinn/"}
  - {name: Martin Mubangizi, url: "http://cit.mak.ac.ug/cs/aigroup/mmubangizi/"}
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com", logo: sheffield.png}
  - {name: Ricardo Andrade Pacheco, url: "http://ric70x7.github.io"}
  - {name: John Quinn, url: "http://cit.mak.ac.ug/staff/jquinn/", logo: makerere.png}
  - {name: Martin Mubangizi, url: "http://cit.mak.ac.ug/cs/aigroup/mmubangizi/"}
  
  name: Gaussian Process School, Uganda
  location: University of Makerere, Kampala, Uganda
  month: August
  year: 2013
  schoolphoto: gps_uganda.jpg
  dates:
  - 2013-08-06
  - 2013-08-07
  - 2013-08-09
# Build settings
markdown: kramdown

analytics:
  google:
    tracking_id: UA-80484960-1

video:
  height: 315
  width: 560

future: true


